---
- name: Create /opt/packages directory
  file:
    path: /opt/packages
    state: directory
  become: yes

- set_fact:
    oauth2_proxy_basename: "oauth2-proxy-{{ oauth2_proxy_version }}.{{ os_dict[ansible_system] }}-{{ arch_dict[ansible_architecture] }}"

- name: Download oauth2-proxy release
  get_url:
    url: "https://github.com/oauth2-proxy/oauth2-proxy/releases/download/{{ oauth2_proxy_version }}/{{ oauth2_proxy_basename }}.tar.gz"
    dest: /opt/packages
  become: yes

- name: Install oauth2-proxy binary
  unarchive:
    src: "/opt/packages/{{ oauth2_proxy_basename }}.tar.gz"
    dest: /opt/packages/
    creates: "/opt/packages/{{ oauth2_proxy_basename }}/oauth2-proxy"
    remote_src: yes
  become: yes

- name: Symlink oauth2-proxy binary
  file:
    src: "/opt/packages/{{ oauth2_proxy_basename }}/oauth2-proxy"
    dest: /usr/bin/oauth2-proxy
    state: link
  become: yes
  register: oauth2_proxy

- name: Copy oauth2-proxy systemd unit template file
  copy:
    src: etc/systemd/system/oauth2-proxy@.service
    dest: /etc/systemd/system/
    mode: '0644'
  become: yes
  register: oauth2_proxy_systemd_unit

- name: Create oauth2-proxy configuration directory
  file:
    path: /etc/oauth2-proxy
    state: directory
  become: yes
