---
- name: Check if nginx exists
  stat:
    path: /sbin/nginx
  register: stat_nginx

- name: "Obtain/renew SSL cert for {{ domain_name }} (via nginx)"
  command: "certbot certonly --nginx -d {{ domain_name }} -m {{ email_address }} --agree-tos -n"
  when: stat_nginx.stat.exists
  become: yes

- name: "Obtain/renew SSL cert for {{ domain_name }} (standalone)"
  command: "certbot certonly --standalone -d {{ domain_name }} -m {{ email_address }} --agree-tos -n"
  when: not stat_nginx.stat.exists
  become: yes
