---
- name: Install strongswan and openssl
  yum:
    name:
      - strongswan
      - openssl
    state: present
  become: yes
  notify:
    - Restart strongswan

- name: Copy sysctl.conf
  copy:
    src: etc/sysctl.d/99-ipsec.conf
    dest: /etc/sysctl.d/
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify:
    - Update sysctl

- name: Copy configuration (common)
  copy:
    src: etc/strongswan/ipsec.conf
    dest: /etc/strongswan/ipsec.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify:
    - Restart strongswan

- name: Copy secrets (common)
  copy:
    src: etc/strongswan/ipsec.secrets
    dest: /etc/strongswan/
    owner: root
    group: root
    mode: '0600'
  become: yes
  notify:
    - Restart strongswan

- name: Create configuration directory
  file:
    path: /etc/strongswan/ipsec.conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Create secrets directory
  file:
    path: /etc/strongswan/ipsec.secrets.d
    state: directory
    owner: root
    group: root
    mode: '0700'
  become: yes

- name: Copy configuration (specific/files)
  copy:
    src: "{{ item }}"
    dest: /etc/strongswan/ipsec.conf.d/
    owner: root
    group: root
    mode: '0644'
  with_fileglob: 
    - files/etc/strongswan/ipsec.conf.d/*.conf
  become: yes
  notify:
    - Restart strongswan

- name: Copy configuration (specific/templates)
  template:
    src: "{{ item }}"
    dest: /etc/strongswan/ipsec.conf.d/
    owner: root
    group: root
    mode: '0644'
  with_fileglob: 
    - templates/etc/strongswan/ipsec.conf.d/*.conf
  become: yes
  notify:
    - Restart strongswan

- name: Copy secrets (specific/files)
  copy:
    src: "{{ item }}"
    dest: /etc/strongswan/ipsec.secrets.d/
    owner: root
    group: root
    mode: '0600'
  with_fileglob: 
    - files/etc/strongswan/ipsec.secrets.d/*
  become: yes
  notify:
    - Restart strongswan

- name: Copy secrets (specific/templates)
  template:
    src: "{{ item }}"
    dest: /etc/strongswan/ipsec.secrets.d/
    owner: root
    group: root
    mode: '0600'
  with_fileglob: 
    - templates/etc/strongswan/ipsec.secrets.d/*
  become: yes
  notify:
    - Restart strongswan

- name: Copy CA certs
  copy:
    src: "{{ item }}"
    dest: /etc/strongswan/ipsec.d/cacerts/
    owner: root
    group: root
    mode: '0644'
  with_fileglob: 
    - files/etc/strongswan/ipsec.d/cacerts/*
  become: yes
  notify:
    - Restart strongswan

- name: Enable service strongswan
  systemd:
    name: strongswan
    enabled: yes
    state: started
  become: yes
