---
- name: Check if EPEL exists
  stat:
    path: /etc/yum.repos.d/epel.repo
  register: stat_epel

- name: Install EPEL repository
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  become: yes
  when: stat_epel.stat.exists == False

# alternative
#- name: Install EPEL repository
#  command:
#    cmd: amazon-linux-extras install epel -y
#    creates: /etc/yum.repos.d/epel.repo
#  become: yes
